name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Generate self-signed cert and .pfx
        run: |
          mkdir -p ./zenra-finance-back
          openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=localhost"
          openssl pkcs12 -export -out ./zenra-finance-back/zenra-finance-back.pfx -inkey key.pem -in cert.pem -passout pass:YourPassword123!
        shell: bash

      - name: Build Docker image
        run: |
          docker build ./zenra-finance-back \
            --file ./zenra-finance-back/Dockerfile \
            --tag zenra-finance-back:latest \
            --tag zenra-finance-back:${{ github.sha }}
